version: "3.0"
services:
  postgres:
    image: postgres
    restart: always
    container_name: mpit2022
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 5qL3F3nRvWf6Jpr5
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres: